-- MySQL Script generated by MySQL Workbench
-- Fri Sep  5 16:55:20 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `Código` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Tel_Celular` VARCHAR(45) NULL,
  PRIMARY KEY (`Código`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Título`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Título` (
  `Código` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Locado` TINYINT NOT NULL,
  PRIMARY KEY (`Código`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Locações`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Locações` (
  `Código` INT NOT NULL,
  `Código_Cliente` INT NOT NULL,
  `Código_Título` INT NOT NULL,
  `Data_Saída` DATE NOT NULL,
  `Data_Retorno` DATE NOT NULL,
  PRIMARY KEY (`Código`),
  INDEX `IDcliente_idx` (`Código_Cliente` ASC) VISIBLE,
  INDEX `IDtitulo_idx` (`Código_Título` ASC) VISIBLE,
  CONSTRAINT `IDcliente`
    FOREIGN KEY (`Código_Cliente`)
    REFERENCES `mydb`.`Cliente` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IDtitulo`
    FOREIGN KEY (`Código_Título`)
    REFERENCES `mydb`.`Título` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
